apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: image2features-gpu-deployment
  labels:
    app: image2features-gpu
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: image2features-gpu
    spec:
      containers:
      - name: image2features-gpu
        image: kikko/image2features:gpu
        imagePullPolicy: Always
        ports:
          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: image2features-gpu-service
spec:
  type: NodePort
  ports:
  - port: 50051
    nodePort: 30007
    targetPort: 50051
  selector:
    app: image2features-gpu
