# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image2faces.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image2faces.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11image2faces.proto\"G\n\x04\x46\x61\x63\x65\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x12\x0f\n\x07\x66\x61\x63\x65net\x18\x05 \x01(\t\"#\n\x12Image2FacesRequest\x12\r\n\x05input\x18\x01 \x01(\x0c\"(\n\x10Image2FacesReply\x12\x14\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\x0b\x32\x05.Face2>\n\x0bImage2Faces\x12/\n\x03Run\x12\x13.Image2FacesRequest\x1a\x11.Image2FacesReply\"\x00\x62\x06proto3')
)




_FACE = _descriptor.Descriptor(
  name='Face',
  full_name='Face',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x1', full_name='Face.x1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y1', full_name='Face.y1', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x2', full_name='Face.x2', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y2', full_name='Face.y2', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='facenet', full_name='Face.facenet', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=92,
)


_IMAGE2FACESREQUEST = _descriptor.Descriptor(
  name='Image2FacesRequest',
  full_name='Image2FacesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='Image2FacesRequest.input', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=129,
)


_IMAGE2FACESREPLY = _descriptor.Descriptor(
  name='Image2FacesReply',
  full_name='Image2FacesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='faces', full_name='Image2FacesReply.faces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=171,
)

_IMAGE2FACESREPLY.fields_by_name['faces'].message_type = _FACE
DESCRIPTOR.message_types_by_name['Face'] = _FACE
DESCRIPTOR.message_types_by_name['Image2FacesRequest'] = _IMAGE2FACESREQUEST
DESCRIPTOR.message_types_by_name['Image2FacesReply'] = _IMAGE2FACESREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Face = _reflection.GeneratedProtocolMessageType('Face', (_message.Message,), dict(
  DESCRIPTOR = _FACE,
  __module__ = 'image2faces_pb2'
  # @@protoc_insertion_point(class_scope:Face)
  ))
_sym_db.RegisterMessage(Face)

Image2FacesRequest = _reflection.GeneratedProtocolMessageType('Image2FacesRequest', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE2FACESREQUEST,
  __module__ = 'image2faces_pb2'
  # @@protoc_insertion_point(class_scope:Image2FacesRequest)
  ))
_sym_db.RegisterMessage(Image2FacesRequest)

Image2FacesReply = _reflection.GeneratedProtocolMessageType('Image2FacesReply', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE2FACESREPLY,
  __module__ = 'image2faces_pb2'
  # @@protoc_insertion_point(class_scope:Image2FacesReply)
  ))
_sym_db.RegisterMessage(Image2FacesReply)



_IMAGE2FACES = _descriptor.ServiceDescriptor(
  name='Image2Faces',
  full_name='Image2Faces',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=173,
  serialized_end=235,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='Image2Faces.Run',
    index=0,
    containing_service=None,
    input_type=_IMAGE2FACESREQUEST,
    output_type=_IMAGE2FACESREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGE2FACES)

DESCRIPTOR.services_by_name['Image2Faces'] = _IMAGE2FACES

# @@protoc_insertion_point(module_scope)
