apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: image2faces-gpu-deployment
  labels:
    app: image2faces-gpu
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: image2faces-gpu
    spec:
      containers:
      - name: image2faces-gpu
        image: gcr.io/cilex-common/image2faces-gpu
        imagePullPolicy: Always
        ports:
          - containerPort: 50051
        resources:
          limits:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: image2faces-gpu-service
spec:
  type: LoadBalancer
  ports:
  - port: 50051
  selector:
    app: image2faces-gpu
