apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: gcr.io/cilex-common/image2faces-gpu
    docker:
      dockerfile: ./deploy/gpu.Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
    - deploy/gpu.k8.yaml