apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: image2faces-gpu-deployment
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - external:
      metricName: container.googleapis.com|container|accelerator|duty_cycle
      targetAverageValue: "20"
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image2faces-gpu-deployment