# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bytes2bytes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bytes2bytes.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x62ytes2bytes.proto\"#\n\x12\x42ytes2BytesRequest\x12\r\n\x05input\x18\x01 \x01(\x0c\"\"\n\x10\x42ytes2BytesReply\x12\x0e\n\x06output\x18\x01 \x01(\x0c\x32>\n\x0b\x42ytes2Bytes\x12/\n\x03Run\x12\x13.Bytes2BytesRequest\x1a\x11.Bytes2BytesReply\"\x00\x62\x06proto3')
)




_BYTES2BYTESREQUEST = _descriptor.Descriptor(
  name='Bytes2BytesRequest',
  full_name='Bytes2BytesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='Bytes2BytesRequest.input', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=56,
)


_BYTES2BYTESREPLY = _descriptor.Descriptor(
  name='Bytes2BytesReply',
  full_name='Bytes2BytesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='Bytes2BytesReply.output', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['Bytes2BytesRequest'] = _BYTES2BYTESREQUEST
DESCRIPTOR.message_types_by_name['Bytes2BytesReply'] = _BYTES2BYTESREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bytes2BytesRequest = _reflection.GeneratedProtocolMessageType('Bytes2BytesRequest', (_message.Message,), dict(
  DESCRIPTOR = _BYTES2BYTESREQUEST,
  __module__ = 'bytes2bytes_pb2'
  # @@protoc_insertion_point(class_scope:Bytes2BytesRequest)
  ))
_sym_db.RegisterMessage(Bytes2BytesRequest)

Bytes2BytesReply = _reflection.GeneratedProtocolMessageType('Bytes2BytesReply', (_message.Message,), dict(
  DESCRIPTOR = _BYTES2BYTESREPLY,
  __module__ = 'bytes2bytes_pb2'
  # @@protoc_insertion_point(class_scope:Bytes2BytesReply)
  ))
_sym_db.RegisterMessage(Bytes2BytesReply)



_BYTES2BYTES = _descriptor.ServiceDescriptor(
  name='Bytes2Bytes',
  full_name='Bytes2Bytes',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=94,
  serialized_end=156,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='Bytes2Bytes.Run',
    index=0,
    containing_service=None,
    input_type=_BYTES2BYTESREQUEST,
    output_type=_BYTES2BYTESREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BYTES2BYTES)

DESCRIPTOR.services_by_name['Bytes2Bytes'] = _BYTES2BYTES

# @@protoc_insertion_point(module_scope)
