apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: gcr.io/{{.PROJECT_ID}}/image2salience-gpu-http
    docker:
      dockerfile: ./deploy/gpu.http.Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
    - deploy/gpu.http.k8.yaml