apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: image2depth-deployment
  labels:
    app: image2depth
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: image2depth
    spec:
      containers:
      - name: image2depth
        image: kikko/image2depth:gpu
        imagePullPolicy: Always
        ports:
          - containerPort: 50051
        resources:
          limits:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: image2depth-service
spec:
  type: NodePort
  ports:
  - port: 50051
    nodePort: 30006
    targetPort: 50051
  selector:
    app: image2depth
