apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: video2flow-deployment
  labels:
    app: video2flow
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: video2flow
    spec:
      containers:
      - name: video2flow
        image: kikko/video2flow:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 50051
        resources:
          limits:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: video2flow-service
spec:
  type: NodePort
  ports:
  - port: 50051
    nodePort: 30003
    targetPort: 50051
  selector:
    app: video2flow
