# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bytes2boxes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bytes2boxes.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x62ytes2boxes.proto\"#\n\x12\x42ytes2BoxesRequest\x12\r\n\x05input\x18\x01 \x01(\x0c\"d\n\x0c\x44\x65tectionBox\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\x12\r\n\x05width\x18\x05 \x01(\x02\x12\x0e\n\x06height\x18\x06 \x01(\x02\"5\n\x10\x42ytes2BoxesReply\x12!\n\ndetections\x18\x01 \x03(\x0b\x32\r.DetectionBox2>\n\x0b\x42ytes2Boxes\x12/\n\x03Run\x12\x13.Bytes2BoxesRequest\x1a\x11.Bytes2BoxesReply\"\x00\x62\x06proto3')
)




_BYTES2BOXESREQUEST = _descriptor.Descriptor(
  name='Bytes2BoxesRequest',
  full_name='Bytes2BoxesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='Bytes2BoxesRequest.input', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=56,
)


_DETECTIONBOX = _descriptor.Descriptor(
  name='DetectionBox',
  full_name='DetectionBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='DetectionBox.category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='DetectionBox.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='DetectionBox.x', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='DetectionBox.y', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='DetectionBox.width', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='DetectionBox.height', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=158,
)


_BYTES2BOXESREPLY = _descriptor.Descriptor(
  name='Bytes2BoxesReply',
  full_name='Bytes2BoxesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detections', full_name='Bytes2BoxesReply.detections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=213,
)

_BYTES2BOXESREPLY.fields_by_name['detections'].message_type = _DETECTIONBOX
DESCRIPTOR.message_types_by_name['Bytes2BoxesRequest'] = _BYTES2BOXESREQUEST
DESCRIPTOR.message_types_by_name['DetectionBox'] = _DETECTIONBOX
DESCRIPTOR.message_types_by_name['Bytes2BoxesReply'] = _BYTES2BOXESREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bytes2BoxesRequest = _reflection.GeneratedProtocolMessageType('Bytes2BoxesRequest', (_message.Message,), dict(
  DESCRIPTOR = _BYTES2BOXESREQUEST,
  __module__ = 'bytes2boxes_pb2'
  # @@protoc_insertion_point(class_scope:Bytes2BoxesRequest)
  ))
_sym_db.RegisterMessage(Bytes2BoxesRequest)

DetectionBox = _reflection.GeneratedProtocolMessageType('DetectionBox', (_message.Message,), dict(
  DESCRIPTOR = _DETECTIONBOX,
  __module__ = 'bytes2boxes_pb2'
  # @@protoc_insertion_point(class_scope:DetectionBox)
  ))
_sym_db.RegisterMessage(DetectionBox)

Bytes2BoxesReply = _reflection.GeneratedProtocolMessageType('Bytes2BoxesReply', (_message.Message,), dict(
  DESCRIPTOR = _BYTES2BOXESREPLY,
  __module__ = 'bytes2boxes_pb2'
  # @@protoc_insertion_point(class_scope:Bytes2BoxesReply)
  ))
_sym_db.RegisterMessage(Bytes2BoxesReply)



_BYTES2BOXES = _descriptor.ServiceDescriptor(
  name='Bytes2Boxes',
  full_name='Bytes2Boxes',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=215,
  serialized_end=277,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='Bytes2Boxes.Run',
    index=0,
    containing_service=None,
    input_type=_BYTES2BOXESREQUEST,
    output_type=_BYTES2BOXESREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BYTES2BOXES)

DESCRIPTOR.services_by_name['Bytes2Boxes'] = _BYTES2BOXES

# @@protoc_insertion_point(module_scope)
