# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bytes2text_pb2 as bytes2text__pb2


class Bytes2TextStub(object):
  """The service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Run = channel.unary_unary(
        '/Bytes2Text/Run',
        request_serializer=bytes2text__pb2.Bytes2TextRequest.SerializeToString,
        response_deserializer=bytes2text__pb2.Bytes2TextReply.FromString,
        )


class Bytes2TextServicer(object):
  """The service definition.
  """

  def Run(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Bytes2TextServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Run': grpc.unary_unary_rpc_method_handler(
          servicer.Run,
          request_deserializer=bytes2text__pb2.Bytes2TextRequest.FromString,
          response_serializer=bytes2text__pb2.Bytes2TextReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Bytes2Text', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
