# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bytes2text.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bytes2text.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x62ytes2text.proto\"\"\n\x11\x42ytes2TextRequest\x12\r\n\x05input\x18\x01 \x01(\x0c\"!\n\x0f\x42ytes2TextReply\x12\x0e\n\x06output\x18\x01 \x01(\t2;\n\nBytes2Text\x12-\n\x03Run\x12\x12.Bytes2TextRequest\x1a\x10.Bytes2TextReply\"\x00\x62\x06proto3')
)




_BYTES2TEXTREQUEST = _descriptor.Descriptor(
  name='Bytes2TextRequest',
  full_name='Bytes2TextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='Bytes2TextRequest.input', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=54,
)


_BYTES2TEXTREPLY = _descriptor.Descriptor(
  name='Bytes2TextReply',
  full_name='Bytes2TextReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='Bytes2TextReply.output', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['Bytes2TextRequest'] = _BYTES2TEXTREQUEST
DESCRIPTOR.message_types_by_name['Bytes2TextReply'] = _BYTES2TEXTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bytes2TextRequest = _reflection.GeneratedProtocolMessageType('Bytes2TextRequest', (_message.Message,), dict(
  DESCRIPTOR = _BYTES2TEXTREQUEST,
  __module__ = 'bytes2text_pb2'
  # @@protoc_insertion_point(class_scope:Bytes2TextRequest)
  ))
_sym_db.RegisterMessage(Bytes2TextRequest)

Bytes2TextReply = _reflection.GeneratedProtocolMessageType('Bytes2TextReply', (_message.Message,), dict(
  DESCRIPTOR = _BYTES2TEXTREPLY,
  __module__ = 'bytes2text_pb2'
  # @@protoc_insertion_point(class_scope:Bytes2TextReply)
  ))
_sym_db.RegisterMessage(Bytes2TextReply)



_BYTES2TEXT = _descriptor.ServiceDescriptor(
  name='Bytes2Text',
  full_name='Bytes2Text',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=91,
  serialized_end=150,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='Bytes2Text.Run',
    index=0,
    containing_service=None,
    input_type=_BYTES2TEXTREQUEST,
    output_type=_BYTES2TEXTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BYTES2TEXT)

DESCRIPTOR.services_by_name['Bytes2Text'] = _BYTES2TEXT

# @@protoc_insertion_point(module_scope)
