apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frames2sift-deployment
  labels:
    app: frames2sift
spec:
  replicas: 4
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: frames2sift
    spec:
      containers:
      - name: frames2sift
        image: kikko/frames2sift
        imagePullPolicy: Always
        ports:
          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: frames2sift-service
spec:
  type: NodePort
  ports:
  - port: 50051
    nodePort: 30005
    targetPort: 50051
  selector:
    app: frames2sift
