# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frames2bytes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frames2bytes.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x66rames2bytes.proto\"5\n\x13\x46rames2BytesRequest\x12\x0e\n\x06\x66rameA\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66rameB\x18\x02 \x01(\x0c\"#\n\x11\x46rames2BytesReply\x12\x0e\n\x06output\x18\x01 \x01(\x0c\x32\x41\n\x0c\x46rames2Bytes\x12\x31\n\x03Run\x12\x14.Frames2BytesRequest\x1a\x12.Frames2BytesReply\"\x00\x62\x06proto3')
)




_FRAMES2BYTESREQUEST = _descriptor.Descriptor(
  name='Frames2BytesRequest',
  full_name='Frames2BytesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameA', full_name='Frames2BytesRequest.frameA', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frameB', full_name='Frames2BytesRequest.frameB', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=75,
)


_FRAMES2BYTESREPLY = _descriptor.Descriptor(
  name='Frames2BytesReply',
  full_name='Frames2BytesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='Frames2BytesReply.output', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['Frames2BytesRequest'] = _FRAMES2BYTESREQUEST
DESCRIPTOR.message_types_by_name['Frames2BytesReply'] = _FRAMES2BYTESREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Frames2BytesRequest = _reflection.GeneratedProtocolMessageType('Frames2BytesRequest', (_message.Message,), dict(
  DESCRIPTOR = _FRAMES2BYTESREQUEST,
  __module__ = 'frames2bytes_pb2'
  # @@protoc_insertion_point(class_scope:Frames2BytesRequest)
  ))
_sym_db.RegisterMessage(Frames2BytesRequest)

Frames2BytesReply = _reflection.GeneratedProtocolMessageType('Frames2BytesReply', (_message.Message,), dict(
  DESCRIPTOR = _FRAMES2BYTESREPLY,
  __module__ = 'frames2bytes_pb2'
  # @@protoc_insertion_point(class_scope:Frames2BytesReply)
  ))
_sym_db.RegisterMessage(Frames2BytesReply)



_FRAMES2BYTES = _descriptor.ServiceDescriptor(
  name='Frames2Bytes',
  full_name='Frames2Bytes',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=114,
  serialized_end=179,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='Frames2Bytes.Run',
    index=0,
    containing_service=None,
    input_type=_FRAMES2BYTESREQUEST,
    output_type=_FRAMES2BYTESREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRAMES2BYTES)

DESCRIPTOR.services_by_name['Frames2Bytes'] = _FRAMES2BYTES

# @@protoc_insertion_point(module_scope)
