# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frames2sift.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frames2sift.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x66rames2sift.proto\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"?\n\x05Match\x12\x11\n\tkeypointA\x18\x01 \x01(\x05\x12\x11\n\tkeypointB\x18\x02 \x01(\x05\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\"4\n\x12\x46rames2SiftRequest\x12\x0e\n\x06\x66rameA\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66rameB\x18\x02 \x01(\x0c\"c\n\x10\x46rames2SiftReply\x12\x1a\n\nkeypointsA\x18\x01 \x03(\x0b\x32\x06.Point\x12\x1a\n\nkeypointsB\x18\x02 \x03(\x0b\x32\x06.Point\x12\x17\n\x07matches\x18\x03 \x03(\x0b\x32\x06.Match2>\n\x0b\x46rames2Sift\x12/\n\x03Run\x12\x13.Frames2SiftRequest\x1a\x11.Frames2SiftReply\"\x00\x62\x06proto3')
)




_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=50,
)


_MATCH = _descriptor.Descriptor(
  name='Match',
  full_name='Match',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keypointA', full_name='Match.keypointA', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keypointB', full_name='Match.keypointB', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='Match.distance', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=115,
)


_FRAMES2SIFTREQUEST = _descriptor.Descriptor(
  name='Frames2SiftRequest',
  full_name='Frames2SiftRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameA', full_name='Frames2SiftRequest.frameA', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frameB', full_name='Frames2SiftRequest.frameB', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=169,
)


_FRAMES2SIFTREPLY = _descriptor.Descriptor(
  name='Frames2SiftReply',
  full_name='Frames2SiftReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keypointsA', full_name='Frames2SiftReply.keypointsA', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keypointsB', full_name='Frames2SiftReply.keypointsB', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matches', full_name='Frames2SiftReply.matches', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=270,
)

_FRAMES2SIFTREPLY.fields_by_name['keypointsA'].message_type = _POINT
_FRAMES2SIFTREPLY.fields_by_name['keypointsB'].message_type = _POINT
_FRAMES2SIFTREPLY.fields_by_name['matches'].message_type = _MATCH
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Match'] = _MATCH
DESCRIPTOR.message_types_by_name['Frames2SiftRequest'] = _FRAMES2SIFTREQUEST
DESCRIPTOR.message_types_by_name['Frames2SiftReply'] = _FRAMES2SIFTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'frames2sift_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  ))
_sym_db.RegisterMessage(Point)

Match = _reflection.GeneratedProtocolMessageType('Match', (_message.Message,), dict(
  DESCRIPTOR = _MATCH,
  __module__ = 'frames2sift_pb2'
  # @@protoc_insertion_point(class_scope:Match)
  ))
_sym_db.RegisterMessage(Match)

Frames2SiftRequest = _reflection.GeneratedProtocolMessageType('Frames2SiftRequest', (_message.Message,), dict(
  DESCRIPTOR = _FRAMES2SIFTREQUEST,
  __module__ = 'frames2sift_pb2'
  # @@protoc_insertion_point(class_scope:Frames2SiftRequest)
  ))
_sym_db.RegisterMessage(Frames2SiftRequest)

Frames2SiftReply = _reflection.GeneratedProtocolMessageType('Frames2SiftReply', (_message.Message,), dict(
  DESCRIPTOR = _FRAMES2SIFTREPLY,
  __module__ = 'frames2sift_pb2'
  # @@protoc_insertion_point(class_scope:Frames2SiftReply)
  ))
_sym_db.RegisterMessage(Frames2SiftReply)



_FRAMES2SIFT = _descriptor.ServiceDescriptor(
  name='Frames2Sift',
  full_name='Frames2Sift',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=272,
  serialized_end=334,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='Frames2Sift.Run',
    index=0,
    containing_service=None,
    input_type=_FRAMES2SIFTREQUEST,
    output_type=_FRAMES2SIFTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRAMES2SIFT)

DESCRIPTOR.services_by_name['Frames2Sift'] = _FRAMES2SIFT

# @@protoc_insertion_point(module_scope)
