# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pose.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pose.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\npose.proto\")\n\x0cPoseSequence\x12\x19\n\x05poses\x18\x01 \x03(\x0b\x32\n.PoseFrame\"-\n\tPoseFrame\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x05poses\x18\x02 \x03(\x0b\x32\x05.Pose\"C\n\x04Pose\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x17\n\x04type\x18\x02 \x01(\x0e\x32\t.PoseType\x12\x16\n\x06points\x18\x03 \x03(\x0b\x32\x06.Point\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02*\'\n\x08PoseType\x12\x1b\n\x17POSE_TYPE_OPENPOSE_FULL\x10\x00\x62\x06proto3')
)

_POSETYPE = _descriptor.EnumDescriptor(
  name='PoseType',
  full_name='PoseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POSE_TYPE_OPENPOSE_FULL', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=204,
  serialized_end=243,
)
_sym_db.RegisterEnumDescriptor(_POSETYPE)

PoseType = enum_type_wrapper.EnumTypeWrapper(_POSETYPE)
POSE_TYPE_OPENPOSE_FULL = 0



_POSESEQUENCE = _descriptor.Descriptor(
  name='PoseSequence',
  full_name='PoseSequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='poses', full_name='PoseSequence.poses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=55,
)


_POSEFRAME = _descriptor.Descriptor(
  name='PoseFrame',
  full_name='PoseFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PoseFrame.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='poses', full_name='PoseFrame.poses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=102,
)


_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Pose.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Pose.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='Pose.points', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=171,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=202,
)

_POSESEQUENCE.fields_by_name['poses'].message_type = _POSEFRAME
_POSEFRAME.fields_by_name['poses'].message_type = _POSE
_POSE.fields_by_name['type'].enum_type = _POSETYPE
_POSE.fields_by_name['points'].message_type = _POINT
DESCRIPTOR.message_types_by_name['PoseSequence'] = _POSESEQUENCE
DESCRIPTOR.message_types_by_name['PoseFrame'] = _POSEFRAME
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.enum_types_by_name['PoseType'] = _POSETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PoseSequence = _reflection.GeneratedProtocolMessageType('PoseSequence', (_message.Message,), dict(
  DESCRIPTOR = _POSESEQUENCE,
  __module__ = 'pose_pb2'
  # @@protoc_insertion_point(class_scope:PoseSequence)
  ))
_sym_db.RegisterMessage(PoseSequence)

PoseFrame = _reflection.GeneratedProtocolMessageType('PoseFrame', (_message.Message,), dict(
  DESCRIPTOR = _POSEFRAME,
  __module__ = 'pose_pb2'
  # @@protoc_insertion_point(class_scope:PoseFrame)
  ))
_sym_db.RegisterMessage(PoseFrame)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(
  DESCRIPTOR = _POSE,
  __module__ = 'pose_pb2'
  # @@protoc_insertion_point(class_scope:Pose)
  ))
_sym_db.RegisterMessage(Pose)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'pose_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  ))
_sym_db.RegisterMessage(Point)


# @@protoc_insertion_point(module_scope)
